### ISSUE TITLE
Does not build in arm64 linux

### ISSUE THREAD

**Issue by jrstrick** [hwittenborn/celeste#109]
Building on rebornOS for Rock5b, librclone-0.3.0 fails to build due to expecting a raw pointer *mut u8 and getting a raw pointer *mut i8.  

Modded cargo.toml to use the current version of librclone (librclone-0.4.0) and it builds without complaint.

Unable to test much further because dropbox has frozen authorizations to this app pending review.

**Comment by hwittenborn** [comment]
Thanks for the issue @jrstrick! I know this reply is quite late, but I'm experiencing this issue while adding support for official arm64 builds, and I'm going to go ahead and get this fixed.

> Unable to test much further because dropbox has frozen authorizations to this app pending review.

That's something that's been long overdue to get fixed, I haven't had much of a chance to get to it yet though. I'm finishing up arm64 support, and then Dropbox/OneDrive support are going to be the next things I tackle.

**Comment by hwittenborn** [comment]
Also see #110 for the Dropbox issue.

**Comment by hwittenborn** [comment]
Oh I guess you made that issue, just keeping that linked for reference then lol.

**Comment by hwittenborn** [comment]
Fixed in [`v0.5.5`](https://github.com/hwittenborn/celeste/releases/tag/v0.5.5).
