### ISSUE TITLE
Endlessly cycles through items in a folder until an item is changed, when it throws an error

### ISSUE THREAD

**Issue by rainspeaker** [hwittenborn/celeste#118]
I set the program to sync my markdown journal files with Google drive (I have them all in one folder). It successfully pulled down all the files very quickly, which I appreciated. But it seems to cycle through the files endlessly rather than ever saying that it has finished checking the directory. Then I went in and modified one of the files. When it hit the modified file in its (endlessly cycling) check, it threw an error, which I didn't manage to screenshot but which I think was something like "directory not found." Then it said it was done checking the directory after I cleared the error. I quit Celeste and restarted; it started cycling through the files again. When it hit the changed file again, it threw an error again--but this time the error was that both the local and the remote copy had been changed since modification. However, this is definitely not true--unless what happened is that Celeste, when it hit the local copy the first time, somehow updated the timestamp on the Google Drive copy and then didn't record that it had finished the upload (or didn't finish the upload). So it seems like there are three (probably connected problems):

1. Celeste doesn't seem to know when to stop checking the director
2. Celeste thought there wasn't a directory where (I think) there was
3. Celeste thought that the local file and remote file had both been updated when that's not so

By the way, I do want to say that I think what you're doing here is incredible and I really appreciate the project. It looks great, I love that you're using such a reliable backend, and the workflow feels like exactly the right approach. I really hope the project goes on to become ubiquitous for cloud syncing on Linux.

**Comment by rainspeaker** [comment]
I reproduced the error. For context, I'm running Celeste in a per-user-installed Flatpak on a fairly fresh Linux Mint install. I reproduced it again starting from the command line, and it looks like the specific thing that failed with "directory not found" was something called "operations/purge." Here's the output from the first error (the second output was the same but without "2023/07/20 17:17:19 ERROR : rc: "operations/purge": error: directory not found"). 

kit@junglegym:~/Desktop/plaintext$ flatpak run com.hunterwittenborn.Celeste

(celeste:18): Adwaita-CRITICAL **: 17:16:55.385: ../src/adw-header-bar.c:640: tried to remove non-child 0x5595853beae0 of type 'GtkButton' from 0x5595850bf380 of type 'AdwHeaderBar'

(celeste:18): Adwaita-CRITICAL **: 17:16:55.386: ../src/adw-header-bar.c:640: tried to remove non-child 0x5595853c9630 of type 'GtkButton' from 0x5595850bf560 of type 'AdwHeaderBar'
Info: Starting up tray binary...
Gtk-Message: 17:16:55.624: Failed to load module "xapp-gtk3-module"
2023/07/20 17:17:19 ERROR : rc: "operations/purge": error: directory not found
Gtk-Message: 17:17:31.775: GtkDialog mapped without a transient parent. This is discouraged.
Warning: Got error while sending close request to tray icon: 'org.freedesktop.DBus.Error.ServiceUnknown: The name com.hunterwittenborn.Celeste.Tray was not provided by any .service files'.

**Comment by hwittenborn** [comment]
Thank you a ton for the bug report and kind words!

> ... it seems to cycle through the files endlessly rather than ever saying that it has finished checking the directory.

That's an issue from how Celeste checks for files - currently once it finished sync checks for all directories it just starts back over at the beginning and repeats the process. It definitely isn't the right way to do it - it's from some early prototyping stages of Celeste, and a new approach hasn't been implemented yet for various reasons.

There's plans (which are pretty much guaranteed to happen, the current syncing approach is basically a bug) for Celeste to only sync when files are actually changed. I've been dabbling at the best way to do it, as I've been looking at various Rust libraries to get the job done but haven't found many. I've got a plan to roll out something custom to get it all working, I just haven't gotten to implementing it all yet.

> ... it looks like the specific thing that failed with "directory not found" was something called "operations/purge."

I've had another user experiencing similar issues to that - would you be able to send over the file the error occurs on (it's above the error message in the UI)?

> When it hit the changed file again, it threw an error again--but this time the error was that both the local and the remote copy had been changed since modification.

I'm not quite sure what might be causing that, though it might be related to the other error above.

The way Celeste handles that feature internally is that it records when the file was last modified, right after it does a successful sync (it's a bit more complicated than that, but that's the gist of it). If Celeste managed to sync the file but not record it in the database I suspect that might be causing the issue.

Is it happening on the same file as the one you had for the `directory not found` error? Does accepting either the remote/local file to keep fix the issue either?

**Comment by coxackie** [comment]
@hwittenborn Many thanks for this wonderful project. Any updates on changing the endless folder cycle of looking for changes?

**Comment by hwittenborn** [comment]
Hey @coxackie, see the linked PR for progress on getting this closed up :)
