### ISSUE TITLE
Flatpak crashes `Failed to load module "canberra-gtk-module"`

### ISSUE THREAD

**Issue by QazCetelic** [hwittenborn/celeste#124]
### Celeste
Arch: x86_64
Branch: stable
Version: 0.5.3
Origin: flathub
Collection: org.flathub.Stable
Installation: system
Runtime: org.gnome.Platform/x86_64/43
Sdk: org.gnome.Sdk/x86_64/43
Commit: cfe0d98a1ff7f962be69c00842f74c34af63fb149763b4cea31344aae100d48f
Parent: 3fe0f3b130b360ed2220b6c08262640be37a6adf31a63344f662864c09cce3c8
Subject: Remove unused permission (87ef7735)
Date: 2023-06-30 13:44:55 +0000

### System
Operating System: openSUSE Tumbleweed 20230814
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.9-1-default (64-bit)
Graphics Platform: X11
The package `libcanberra-gtk-module-common-0.30-15.27.x86_64` is installed.

```
flatpak run com.hunterwittenborn.Celeste                                                                                                                                                                                           (base) 

(process:2): Gtk-WARNING **: 11:00:34.611: Locale not supported by C library.
        Using the fallback 'C' locale.

(process:33): Gtk-WARNING **: 11:00:34.698: Locale not supported by C library.
        Using the fallback 'C' locale.

(celeste:33): Adwaita-CRITICAL **: 11:00:34.800: ../src/adw-header-bar.c:640: tried to remove non-child 0x5651a0475c60 of type 'GtkButton' from 0x5651a0061380 of type 'AdwHeaderBar'

(celeste:33): Adwaita-CRITICAL **: 11:00:34.800: ../src/adw-header-bar.c:640: tried to remove non-child 0x5651a048b7d0 of type 'GtkButton' from 0x5651a0061560 of type 'AdwHeaderBar'
Info: Starting up tray binary...

(process:113): Gtk-WARNING **: 11:00:34.863: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 11:00:34.864: Failed to load module "canberra-gtk-module"
```

**Comment by DaisyLee2010** [comment]
Also seeing this on pop_OS 

`$ flatpak run com.hunterwittenborn.Celeste

(celeste:29): Adwaita-CRITICAL **: 22:35:51.430: ../src/adw-header-bar.c:640: tried to remove non-child 0x5584837acc70 of type 'GtkButton' from 0x55848334e380 of type 'AdwHeaderBar'

(celeste:29): Adwaita-CRITICAL **: 22:35:51.430: ../src/adw-header-bar.c:640: tried to remove non-child 0x5584837c47c0 of type 'GtkButton' from 0x55848334e560 of type 'AdwHeaderBar'
Info: Starting up tray binary...
Gtk-Message: 22:35:51.571: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:35:51.572: Failed to load module "canberra-gtk-module"
thread 'main' panicked at /root/stage/usr/share/rust/registry/src/index.crates.io-6f17d22bba15001f/libappindicator-sys-0.7.3/src/lib.rs:41:5:
Failed to load ayatana-appindicator3 or appindicator3 dynamic library
libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
libappindicator3.so.1: cannot open shared object file: No such file or directory
libayatana-appindicator3.so: cannot open shared object file: No such file or directory
libappindicator3.so: cannot open shared object file: No such file or directory
stack backtrace:
   0: rust_begin_unwind
             at /rustc/960754090acc9cdd2a5a57586f244c0fc712d26c/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/960754090acc9cdd2a5a57586f244c0fc712d26c/library/core/src/panicking.rs:72:14
   2: core::ops::function::FnOnce::call_once
   3: once_cell::imp::OnceCell<T>::initialize::{{closure}}
   4: once_cell::imp::initialize_or_wait
   5: once_cell::imp::OnceCell<T>::initialize
   6: libappindicator_sys::app_indicator_new
   7: libappindicator::AppIndicator::new
   8: celeste_tray::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

(celeste:2): GLib-CRITICAL **: 22:35:57.918: Failed to set scheduler settings: Operation not permitted
`

**Comment by hwittenborn** [comment]
@DaisyLee2010: Your issue is due to a missing library that's in the Flatpak, which was recently fixed in the latest release. It should be out on Flathub in a few hours (publishes have a 3 hour delay on Flathub iirc).

@QazCetelic: I'm not sure what's going on with you, sorry for the delayed response on my part but are you still experiencing this issue?

**Comment by QazCetelic** [comment]
Yes, it crashes a few seconds after opening it.

[CelesteCrash.webm](https://github.com/hwittenborn/celeste/assets/51381523/fa0502d4-ba87-48fa-9d2f-a3ddc31ccd8d)

`flatpak info com.hunterwittenborn.Celeste` results:
```
Celeste - Sync your cloud files

          ID: com.hunterwittenborn.Celeste
         Ref: app/com.hunterwittenborn.Celeste/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.7.0
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 118.8?MB
     Runtime: org.gnome.Platform/x86_64/43
         Sdk: org.gnome.Sdk/x86_64/43

      Commit: b6663eb93b7eee0cb2ffe2929620f8d7305eb3fd28d0ddff1ef8d3b25195ac79
      Parent: 58ff3ad4c242a51e3e413d5c435c5e5421dbe3edfbc463e29a7feecd9535f91a
     Subject: Update package version (4e4c7736)
        Date: 2023-10-08 01:39:26 +0000
```

**Comment by DaisyLee2010** [comment]
That did indeed fix my issue. Thank you @hwittenborn

**Comment by hwittenborn** [comment]
@QazCetelic: I think your issue should be fixed by https://github.com/flathub/com.hunterwittenborn.Celeste/pull/30. I just need to get the build in that PR fixed up first.

@DaisyLee2010: Glad to hear it's all good for you :). Feel free to make a new issue if you experience any other problems.

**Comment by QazCetelic** [comment]
I can't reproduce this using 0.8.1
