### ISSUE TITLE
process /tmp/.tmpfuO3J6 hogs CPU when celeste connected to onedrive

### ISSUE THREAD

**Issue by SmartLayer** [hwittenborn/celeste#128]
process /tmp/.tmpfuO3J6 hogs CPU when celeste connected to onedrive this is observed even when the process of celeste is killed.

I'm not sure if it is even related to celeste but if you feel unrelated you can close this

**Comment by hwittenborn** [comment]
Thanks for the issue @SmartLayer! This seems like the same stuff as https://github.com/hwittenborn/celeste/issues/36#issuecomment-1424760731 - it's Celeste tray icon (which runs as a separate application) that appears to be hogging your system's resources. I'm currently working on reworking the tray icon application (I'm going to be removing it and making it run under the same process as the main app), which should hopefully fix up that issue.
