### ISSUE TITLE
Proton Login not working

### ISSUE THREAD

**Issue by mufeedali** [hwittenborn/celeste#153]
![celeste_repor](https://github.com/hwittenborn/celeste/assets/28823274/8f2b2c2b-a639-4c8b-9f5a-74a0ced0e9ee)

Possibly relevant log:
```
2023/10/08 12:44:19.614956 ERROR RESTY 401 GET https://mail.proton.me/api/core/v4/users: Invalid access token (Code=401, Status=401), Attempt 1
2023/10/08 12:44:20.426586 ERROR RESTY 422 POST https://mail.proton.me/api/auth/v4/refresh: Invalid refresh token (Code=10013, Status=422), Attempt 1
```

**Comment by hwittenborn** [comment]
Hey @mufeedali, are you using the Flatpak? I've noticed the issue on there, though I haven't been able to pin down why yet.

**Comment by hwittenborn** [comment]
Those errors you saw always happen on a fresh login, they should be safe to ignore

**Comment by mufeedali** [comment]
Yep, it's the flatpak. I assumed flatpak was the only official way to install it?

**Comment by hwittenborn** [comment]
There's also the [Snap](https://github.com/hwittenborn/celeste?tab=readme-ov-file#snap) and [Prebuilt-MPR](https://github.com/hwittenborn/celeste?tab=readme-ov-file#prebuilt-mpr-debianubuntu) if you have either of those on your system. Would you be able to give any of those a shot?

If not that's fine too, I'm actively looking into what's causing the Flatpak to act up.

**Comment by mufeedali** [comment]
```
Failed to load ayatana-appindicator3 or appindicator3 dynamic library
libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
libappindicator3.so.1: cannot open shared object file: No such file or directory
libayatana-appindicator3.so: cannot open shared object file: No such file or directory
libappindicator3.so: cannot open shared object file: No such file or directory
stack backtrace:
   0: rust_begin_unwind
             at /rustc/960754090acc9cdd2a5a57586f244c0fc712d26c/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/960754090acc9cdd2a5a57586f244c0fc712d26c/library/core/src/panicking.rs:72:14
   2: core::ops::function::FnOnce::call_once
   3: once_cell::imp::OnceCell<T>::initialize::{{closure}}
   4: once_cell::imp::initialize_or_wait
   5: once_cell::imp::OnceCell<T>::initialize
   6: libappindicator_sys::app_indicator_new
   7: libappindicator::AppIndicator::new
   8: celeste_tray::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mufeedali** [comment]
Maybe this is why

**Comment by hwittenborn** [comment]
Ohh actually that might be what's causing the issue, is that where you're seeing the freezing at, or do you no longer see the login screen?

That issue you posted should've been resolved in a Flathub release a few hours ago, I'm not quite sure why it hasn't been deployed yet, but I'll give that all a look.

**Comment by hwittenborn** [comment]
How long ago did you install the Flatpak? Could you try checking if there's updates available for it?

**Comment by mufeedali** [comment]
Yep, got the update. Working now!

**Comment by hwittenborn** [comment]
Oh cool, glad to hear that fixed it up! I'll go ahead and get this closed then, feel free to reach out if you have any other issues :)
