### ISSUE TITLE
Can't use the application, freeze when adding Google Drive

### ISSUE THREAD

**Issue by gremo** [hwittenborn/celeste#154]
Hello, thanks for you app, I really like to enjoy it but it seems it doesn't work at least on my setup. When I start the application and choose "Google Drive", clicking "Log in" just freeze the window forever:

![Screenshot from 2023-10-08 19-41-07](https://github.com/hwittenborn/celeste/assets/1532616/298bd48b-aba8-4ac7-b432-05c04657124e)

Can you help me understand what's happening here?

Thanks

**Comment by hwittenborn** [comment]
Are you using the Flatpak @gremo? That's where I've been seeing the issue happen recently.

**Comment by gremo** [comment]
@hwittenborn Yes, I'm using the Flatpak version!

**Comment by hwittenborn** [comment]
Hey @gremo, sorry for the late response but I've managed to find the cause of this issue and get it fixed up. See https://github.com/hwittenborn/celeste/issues/161#issuecomment-1817710686 for more info on that, and feel free to continue the conversation there if you're still having any related issues :)
