### ISSUE TITLE
Celeste is trying to sync files even when no files have been changed

### ISSUE THREAD

**Issue by danielbmeireles** [hwittenborn/celeste#168]
Hello!

My Celeste client is checking the Dropbox server every second (apparently).

I cannot find the functionality/option to only run sync checks when files are changed.

**Comment by tomtom7899** [comment]
I have the same issue while syncing with google drive. I have 0.8.0 installed from apt on Ubuntu 23.04.

**Comment by elydpg** [comment]
I have the same issue. 0.8.0 installed from Flatpak on Kubuntu 23.10

**Comment by Froggy232** [comment]
Same issue here, the file get checked every seconds.
Does someone have a solution?

**Comment by hwittenborn** [comment]
Hey all, I'm not entirely positive what might be causing this issue still. Celeste doesn't currently expose a bunch of debug information to find this out with, though I'm suspecting this might be due to files that didn't get synced because of permission errors.

Would any of y'all be able to try running this command on the local directory you're syncing? I'm mostly curious if it returns a permission error or anything of the sort:

```sh
file /sync/dir/path 1> /dev/null
```

**Comment by Froggy232** [comment]
Hi,
Thanks for your answer!
I need to tell that I use nextcloud, not dropbox. But except that, everything is the same, as the app recheck the files very very frequently.
I have typed the command you write in a terminal, but it return me literally nothing.
Thanks you

**Comment by hwittenborn** [comment]
Alright, I'm pretty sure that means the issue I was suspecting isn't the case @Froggy232. I'll do some more looking to see what I can find and let y'all know if I uncover anything though.

**Comment by Pkcarreno** [comment]
> I'm suspecting this might be due to files that didn't get synced because of permission errors.

![image](https://github.com/hwittenborn/celeste/assets/34664891/7cb66767-5387-45e3-9a00-38f2f8f5adf8)
Maybe that you are mention it's related to this error message, even if I reboot the system it happens immediately, but everything is ok in folder

**Comment by hwittenborn** [comment]
There's no errors that show in the UI @Pkcarreno? If so that's probably just a bug with the tray implementation, as all errors in Celeste get added to the error list immediately when they occur.

**Comment by Pkcarreno** [comment]
> There's no errors that show in the UI @Pkcarreno? If so that's probably just a bug with the tray implementation, as all errors in Celeste get added to the error list immediately when they occur.

That makes sense, there is no error in app
Btw, thanks for this awesome app!
