### ISSUE TITLE
Weblate translations

### ISSUE THREAD

**Issue by sabriunal** [hwittenborn/celeste#183]
It appears that translations for several languages have been completed but are still awaiting merging on Weblate.

My translations have been in the queue for four months.

Could you please merge them, or should I resend them from GitHub?

**Comment by hwittenborn** [comment]
Hey @sabriunal, terribly sorry for the delay. I've gotten quite busy on my part, and I completely lost track of getting translations updated.

I'm waiting for the CI to pass on translations, and then this should be all good to go though. I'll send a message here once that's all complete.

**Comment by hwittenborn** [comment]
Alright things should be good to go now @sabriunal, sorry for any delay this might've caused. Let me know if you notice anything else though!
