### ISSUE TITLE
[Bug]: Unknown Error

### ISSUE THREAD

**Issue by darvo90** [hwittenborn/celeste#234]
### Bug Description

The error below happens randomly during syncronization with Celeste closed to the tray

thread 'main' panicked at src/launch.rs:2489:33:
internal error: entered unreachable code
stack backtrace:
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x6142a00c5905 - <unknown>
   1:     0x6142a00f45eb - <unknown>
   2:     0x6142a00c1ecf - <unknown>
   3:     0x6142a00c56de - <unknown>
   4:     0x6142a00c6c29 - <unknown>
   5:     0x6142a00c69cc - <unknown>
   6:     0x6142a00c7201 - <unknown>
   7:     0x6142a00c7033 - <unknown>
   8:     0x6142a00c5dc9 - <unknown>
   9:     0x6142a00c6d44 - <unknown>
  10:     0x6142a00f1565 - <unknown>
  11:     0x6142a00f15f2 - <unknown>
  12:     0x6142a00f1736 - <unknown>
  13:     0x61429e1f1f04 - <unknown>
  14:     0x7f7bf2d7143a - g_closure_invoke
  15:     0x7f7bf2d8596c - <unknown>
  16:     0x7f7bf2d873f1 - <unknown>
  17:     0x7f7bf2d8d3c1 - g_signal_emit_valist
  18:     0x7f7bf2d8d483 - g_signal_emit
  19:     0x7f7bf20fe9b8 - <unknown>
  20:     0x7f7bf20feb1b - g_application_run
  21:     0x61429e0baec8 - <unknown>
  22:     0x61429e1620e7 - <unknown>
  23:     0x61429e295a63 - <unknown>
  24:     0x61429e195c79 - <unknown>
  25:     0x6142a00b9782 - <unknown>
  26:     0x61429e165205 - <unknown>
  27:     0x7f7bf1c0c08a - <unknown>
  28:     0x7f7bf1c0c14b - __libc_start_main
  29:     0x61429e07c025 - <unknown>
  30:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.

### Installation Source

Flatpak

### What version of Celeste are you using?

0.8.3

### Storage Provider

Google Drive

**Comment by curiousmike** [comment]
Just had the exact same crash - flatpak, google drive, same crash stack.
Also - when trying to see the version, when I try to do the "What's new" menu item I see "Unable to parse release notes:
Unexpected element 'description'
Line: 2, character: 1"
