### ISSUE TITLE
Nextcloud remote folder don't exist

### ISSUE THREAD

**Issue by PrzemekSkw** [hwittenborn/celeste#24]
Hello, is there any guide how to configure Nextcloud. How to enter path of remote folder?

**Comment by hwittenborn** [comment]
Does the remote folder you're trying to add already exist on Nextcloud? If it doesn't I don't think Celeste supports setting up the sync directory from there, but there could probably be a prompt added to create it for you.

Or is it with an existing one and it just isn't working?

**Comment by hwittenborn** [comment]
You should put the path how you'd see it in the Nextcloud web UI (i.e. a `Documents` folder that'd you'd see when opening up the Nextcloud file browser would be accessed from `/Documents/`).

If that doesn't work, could you send over the error message you're getting?

**Comment by PrzemekSkw** [comment]
Do You mean `https://myservername/apps/files/?dir=/Documents&fileid=16` ?
I try that and it don't work.

**Comment by hwittenborn** [comment]
No, just `/Documents/`, that's my bad for not being more specific. If just putting `/Documents/` doesn't work can you send over a screenshot of the error, or at least the text of it?

**Comment by PrzemekSkw** [comment]
First when I choose local folder I get this:
![image](https://user-images.githubusercontent.com/25219988/217730212-e2e5a6c3-634d-404c-8671-37f702b344e5.png)
It means: `Cannot display content of folder. Action has been cancelled.`

then when I choose remote:
![image](https://user-images.githubusercontent.com/25219988/217729965-057a36a1-cdef-4d43-bb7a-dd07034dcc6f.png)

**Comment by hwittenborn** [comment]
Are you sure that `Documents/` exists on your Nextcloud server? I haven't been having any issues, and Nextcloud is the primary thing I use with Celeste.

Would you be able to try removing the Nextcloud remote and readding it too? There might've been some issue during upgrades from one version of Celeste to the next. I don't think there was, but it wouldn't hurt to try to see if it fixes anything.

**Comment by PrzemekSkw** [comment]
![Screenshot_2023-02-09-15-46-45-85_06ea656a9ba653ff96746f477f32d0f9](https://user-images.githubusercontent.com/25219988/217846057-5c1b63c1-0e52-4aa2-8f49-7c294563942c.jpg)

**Comment by PrzemekSkw** [comment]
Meybe my docker installation is a problem?

**Comment by hwittenborn** [comment]
Are you saying you have Celeste installed inside of Docker? It'd probably be better to try from the Snap/Flatpak if so just to see if you can reproduce the issue.

**Comment by PrzemekSkw** [comment]
No Nextcloud in Docker (DockStarter). Celeste in flatpak.

**Comment by hwittenborn** [comment]
Hmm, I'm not quite sure what's up then. I can say that I've connected to Nextcloud just fine and haven't had any issues.

If you're using the WebDAV server type, you just add `remote.php/dav/${USER}/files` at the end of the URL. May you could try that?

If you're having an issue I definitely want to get it solved though. I'm not quite sure what's up, but we can get it figured out still if you want to keep giving it a shot.

**Comment by PrzemekSkw** [comment]
@hwittenborn Hi, I have the same situation in AUR package. Is there any logs I could find from Celeste?

**Comment by PrzemekSkw** [comment]
Hi, I have something like this:
```
(.tmpObWhr7:25840): Gtk-CRITICAL **: 18:23:39.172: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(.tmpObWhr7:25840): Gtk-CRITICAL **: 18:23:39.673: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(.tmpObWhr7:25840): Gtk-CRITICAL **: 18:23:39.675: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
Adwaita-Message: 18:23:40.380: AdwMessageDialog mapped without a transient parent. This is discouraged.

(.tmpObWhr7:25840): Gtk-CRITICAL **: 18:23:45.746: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(.tmpObWhr7:25840): Gtk-CRITICAL **: 18:23:45.749: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(.tmpObWhr7:25840): Gtk-CRITICAL **: 18:23:46.251: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by hwittenborn** [comment]
Hmm, there isn't anything that might be causing issues in that output. I'll do some debugging when I get home just to make sure everything's looking right, there are a few spots in the codebase I'm wanting to give a quick check over.

Just asking to make sure, but could you check that you're on the latest version?

**Comment by PrzemekSkw** [comment]
I think there's no way to install old AUR version. Meybe there's some problem because SSL?

**Comment by hwittenborn** [comment]
Are you trying to install an older version for any particular reason? What error are you getting too?

**Comment by PrzemekSkw** [comment]
I have now AUR last version installed.

**Comment by hwittenborn** [comment]
Alright, thanks a ton @PrzemekSkw. I haven't found a solution yet, but I'll give this another look once I'm at home.

**Comment by PrzemekSkw** [comment]
Meybe it's problem because I have Nextcloud in Docker and SSL from Nginx Proxy Manager. I also generate API token for Celeste app and don't login with my admin credentials.
But I also do that for other apps: Thunderbird, Cardbook (Thunderbird) and Fenrus. All works great.

**Comment by hwittenborn** [comment]
I wouldn't think so, as long as other things can access your Nextcloud instance just fine then it's probably just an issue with Celeste.

Would you be able to try logging in to any of the other storage backend (such as Google Drive or Dropbox)? That'd at least help to determine if it's just an issue with the Nextcloud integration or not.

**Comment by PrzemekSkw** [comment]
I cant login to Google because I get warrning abut aplication is blocked.
Can You tell me it's normal view if I have login to Nextcloud but not add folders yet?
![image](https://user-images.githubusercontent.com/25219988/219132790-28b09241-09bf-49a8-849d-3e46618aa0a4.png)

**Comment by Boricua3** [comment]
Hi. Sorry if I'm a little late to this topic. I just installed Celeste on Fedora 39 Silverblue and found this exact same issue. I tried with Flatseal adding acces to my failes, but the behavior remains the same. I'm using the latest Flatpak version.

**Comment by qntnlq** [comment]
Hello,

Maybe we should reopen this issue. I came up with this exact same error. I'm on Silverblue with the Flatpak version of Celeste.
I'm trying to sync my logseq journal that I have setup locally : 
![Capture d’écran du 2024-04-03 19-08-20](https://github.com/hwittenborn/celeste/assets/106921026/41476cab-b511-4b6d-a290-85c5e0fe81a3)
The path to this folder is `/var/home/quentin/logseq/`

I have created a Nextcloud folder in my Documents : 
![Capture d’écran du 2024-04-03 19-07-25](https://github.com/hwittenborn/celeste/assets/106921026/da6985fd-feac-4504-88b0-aa1ee7aa9a5f)
So the remote folder path should be, if I am not mistaken,` /Documents/logseq/`

This is what I tried : 
![Capture d’écran du 2024-04-03 19-12-55](https://github.com/hwittenborn/celeste/assets/106921026/76b19206-55f9-4f26-813e-00d94a6dcc07)

And I get this same message : `The specified remote directory doesn't exist`.

Maybe there is a problem on my end, but if I understood correctly what was written in this issue, I should have written the correct path. If you need more data, an app log or anything, I'd gladly help.

Thanks in advance !

**Comment by McBaumwolle** [comment]
I'm having the same issues as stated in https://github.com/hwittenborn/celeste/issues/24#issuecomment-1423677059 and cannot get this to work.

**Comment by jerem62** [comment]
Same issue here, is there any solution or workarround ?
