### ISSUE TITLE
Main thread panicks when reading local directory with trailing slash

### ISSUE THREAD

**Issue by FloEdelmann** [hwittenborn/celeste#26]
After saving a folder pair with `/home/flo/Dokumente/` as the local folder, the whole application crashed with the following error message:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', celeste/src/launch.rs:1594:34
```

When starting the application again, it crashes approximately half a second after the main window comes up, so I have no chance to interact with it.

The relevant source line:

https://github.com/hwittenborn/celeste/blob/da2f91350cd8c0de3537ed77f8980e81a84ba6d5/celeste/src/launch.rs#L1592-L1594

I installed version v0.3.5 via Flatpak.

**Comment by FloEdelmann** [comment]
Changing the directory to `/home/flo/Dokumente` (without trailing slash) via the *DB Browser for SQLite* in the `sync_dirs` table in `/home/flo/.var/app/com.hunterwittenborn.Celeste/config/celeste/celeste.db` avoids the crash.

But then all remote directories are not synced as separate items inside `/home/flo/Dokumente` (e.g. `/home/flo/Dokumente/Music`), but rather `/home/flo/DokumenteMusic` etc.

**Comment by hwittenborn** [comment]
I can confirm the trailing slash issue causes a panic, I've got to get a few things done but I'll have fix out by the end of the day.

> But then all remote directories are not synced as separate items inside /home/flo/Dokumente (e.g. /home/flo/Dokumente/Music), but rather /home/flo/DokumenteMusic etc.

I was able to confirm that issue too. That one might require a bit more investigating too, but if not tonight I'll have a fix out tomorrow.

**Comment by hwittenborn** [comment]
> But then all remote directories are not synced as separate items inside /home/flo/Dokumente (e.g. /home/flo/Dokumente/Music), but rather /home/flo/DokumenteMusic etc.

@julianfairfax I'm gonna fix this part tonight, and then the Flatpak should be out within a few hours of that, so pretty likely both tonight, if not it'll be soon after.

**Comment by hwittenborn** [comment]
@FloEdelmann @julianfairfax The changes are being deployed right now, and should be out to the Flatpak within a few hours. I'll send a message here once it's available to download from Flathub.

**Comment by FloEdelmann** [comment]
Thanks, I confirm that it works with the latest Flatpak version now :slightly_smiling_face:

**Comment by hwittenborn** [comment]
> Error now is
>
> ```
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', celeste/src/launch.rs:1841:54
> stack backtrace:
> ```

Does that happen every time you open up Celeste, or just sometimes?

**Comment by hwittenborn** [comment]
Thanks for letting me know @julianfairfax, I'll give this a look soon to see if I can find out what's causing the issue.
