### ISSUE TITLE
Add pCloud storage type

### ISSUE THREAD

**Issue by RayJW** [hwittenborn/celeste#27]
It would be nice if you could also add compatibility with [pCloud Storage](https://www.pcloud.com/eu). They have an API documented [here](https://docs.pcloud.com/) and also some SDK's (no rust though, sadly).

**Comment by hwittenborn** [comment]
Yeah that's fine. Celeste actually uses [rclone](rclone.org/) to sync files which already appears to have a [pCloud backend](https://rclone.org/pcloud/), so that should be fine enough to implement. I'll let you know when I have something going :)

**Comment by RayJW** [comment]
Thanks for the quick answer, amazing work you're doing there! Could you also simulate their functionality where you see all the files in the file manager but only download them on demand once they're opened?
That's a really convenient feature overall, but their client seems to be quite spotty with syncing performance, which is why I'm always on the lookout for alternatives.

**Comment by hwittenborn** [comment]
> Could you also simulate their functionality where you see all the files in the file manager but only download them on demand once they're opened?

I'd have to look into how that's done honestly, part of me's thinking there's gotta be some kernel stuff going on, in which case I'll probably be doing a lot of research figuring out how to make that work. I've got a few other feature requests to handle (including adding pCloud storage support itself), but I'll get this part specifically a look after all that's done.

**Comment by RayJW** [comment]
Yes, I totally understand that getting all the integrations running is the highest priority atm. Just to give you an idea of a workflow profiting of this. If you do photography and have your pictures in the cloud, you don't want to constantly sync 100s of GB's on your device. However, ideally they are still available in your picture management software and downloaded once you actually want to edit / manage a certain picture.
I hope that makes sense, and thanks again for your amazing work on this! :)

**Comment by hwittenborn** [comment]
pCloud support just got added in https://github.com/hwittenborn/celeste/commit/6cdb76481bb4c34313a069520cf6eaa2b107c11d, it'll be deployed to all platforms within a few hours.

Could you make another issue about the simulated file stuff? I want to go ahead and close this one because the original issue was solved, and it'll make it cleaner to read the comments if that all is in a new issue

**Comment by hwittenborn** [comment]
Just FYI on why the Snap/Flatpak hasn't been updated yet - there was a failed build before I went to sleep last night, and I didn't notice it until I woke up this morning. I'm getting it deployed again right now though, and it should be out in about 3 hours.
