### ISSUE TITLE
Add Proton Drive support

### ISSUE THREAD

**Issue by noverby** [hwittenborn/celeste#31]

**Comment by Samillion** [comment]
:O I didn't even know this was possible, Nice!

**Comment by noverby** [comment]
@Samillion Nevermind it is not: https://github.com/rclone/rclone/issues/6072

**Comment by hwittenborn** [comment]
Yeah what @noverby said. It's definitely something I want to add if I could, just the fact that Proton Drive doesn't have a public API makes that basically unmanageable. If they support such in the future I'll definitely get it added though.

**Comment by ayykamp** [comment]
Take a look at rclone/rclone#6072 again :)

**Comment by noverby** [comment]
@ayykamp Nice!

**Comment by noverby** [comment]
@hwittenborn so are you still interested in adding Proton Drive support? :)

**Comment by hwittenborn** [comment]
That's great to see @ayykamp! I'm definitely interested in getting this going then @noverby, I'll always be one with adding anything that's supported by rclone (except for some remotes like Google Photos that don't make a ton of sense for file syncing).

I'm currently working on a few major issues with Celeste, so I can't give an ETA when it'll be completed. This is definitely on my radar considering the popularity of Proton's services though!

**Comment by RayJW** [comment]
Just in case, this flew under the radar. Rclone 1.64 added [support for Proton Drive](https://rclone.org/changelog/#v1-64-0-2023-09-11)! :)

**Comment by hwittenborn** [comment]
Thanks for the update @RayJW! I hadn't mentioned it, but I was waiting for Proton Drive to get into a stable rclone release before doing much with it. Now that it's all there I shouldn't have any issues getting it added into Celeste though.

I'm working on a few issues with other backends at the moment (notably Dropbox and Google Drive), but I'll get this looked at after I get those figured out.

**Comment by hwittenborn** [comment]
Proton Drive should now be available in [`v0.6.0`](https://github.com/hwittenborn/celeste/releases/tag/v0.6.0).

I'd like to note that if you're using a [two-step password](https://proton.me/support/single-password#two-password-mode) that you won't be able to log in currently. It wouldn't have been much extra work to add support for the second password to the UI, but I was thinking it'd create confusion for new users who don't know what that is, and I ultimately decided on excluding it.

If there's any demand for it I'm more than glad to look back into implementing it though, just let me know if that's the case for any of y'all.
