### ISSUE TITLE
verify your app with Google.

### ISSUE THREAD

**Issue by tazihad** [hwittenborn/celeste#38]
Can you please verify your app with Google. So, that we don't get spooky warning. 
![Screenshot_20230209_131527](https://user-images.githubusercontent.com/19417232/217743708-61a9e211-45c0-4b6a-9ce6-d7a496071d7d.png)

**Comment by FloEdelmann** [comment]
See #30

**Comment by hwittenborn** [comment]
Yeah, track that issue for the progress on getting this resolved. I'm working on getting this fixed soon though @tazihad.
