### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by Vistaus** [hwittenborn/celeste#40]
It would be great if the app could be translated. I'll provide the Dutch translation once this is possible.

**Comment by Henryws** [comment]
I could help with Spanish.

**Comment by hwittenborn** [comment]
I've got to get these remaining bug issues closed up, then this'll come next. That should hopefully be within a few days, I'll send something once I got translations going though.

**Comment by hwittenborn** [comment]
Translation support is now live here: https://weblate.makedeb.org/projects/hwittenborn/celeste/. Feel free to send another message here if you have issues with starting translations.

**Comment by Vistaus** [comment]
Thank you for providing support! However, I can't start a new translation as it says that the repository can't be pushed to, so the translation is locked.

**Comment by Henryws** [comment]
Same.

**Comment by hwittenborn** [comment]
@Vistaus @Henryws: Looks like there was some issue that made the repository get locked (I'm not quite sure why yet) - it should be good now though, could y'all check if it's working fine on your end?

**Comment by Henryws** [comment]
Works.

**Comment by Vistaus** [comment]
Works for me too. Thanks, @hwittenborn !

**Comment by hwittenborn** [comment]
Just sending a heads up, but the Weblate instance used for translations has changed now (see https://github.com/hwittenborn/celeste#translating). The makedeb Weblate instance is proving to be a bit burdensome to maintain, and I think I'm going to start phasing it out in turn for the official one mention in that link.
