### ISSUE TITLE
There was an issue authenticating to Google Drive

### ISSUE THREAD

**Issue by gonzoknows** [hwittenborn/celeste#43]
It says `rclone.conf` was not found and `tcp 127.0.0.1` was already in use.

Server Type - `Google Drive (School Account)`
Server Name - `drive.google.com`

**Comment by FabioLolix** [comment]
Hello, I'm using v0.4.0  and isn't working for me too, it had opened the link in browser once but authentication didn't go well and now refuse to open the link in browser again

```
 $celeste
2023/02/09 18:58:09 NOTICE: Config file "/home/fabio/.config/celeste/rclone.conf" not found - using defaults
Adwaita-Message: 18:58:20.802: AdwMessageDialog mapped without a transient parent. This is discouraged.
Adwaita-Message: 18:58:21.309: AdwMessageDialog mapped without a transient parent. This is discouraged.
```

btw I can't copy the error message from the window so there is the screenshot

![celeste](https://user-images.githubusercontent.com/19638095/217900477-f695a06e-d221-4742-a1e0-9356fe9a8b01.png)

**Comment by hwittenborn** [comment]
> and `tcp 127.0.0.1` was already in use.

That's a bug that occurs from clicking `Cancel` on the login popup, I'm gonna look into it tonight and try to get a fix in. You can run the following to manually fix the issue, which should then allow you to try logging in again:

```sh
sudo ss --kill state listening src ':53682'
```

@gonzoknows @FabioLolix Let me know if you still can't log in after that, and I'll see if something's up with the Google Drive integration. Last time I checked it was working fine, but I'll give it a look if you guys are still having issues.

**Comment by gonzoknows** [comment]
> > and `tcp 127.0.0.1` was already in use.
> 
> That's a bug that occurs from clicking `Cancel` on the login popup, I'm gonna look into it tonight and try to get a fix in. You can run the following to manually fix the issue, which should then allow you to try logging in again:
> 
> ```shell
> sudo ss --kill state listening src ':53682'
> ```
> 
> @gonzoknows @FabioLolix Let me know if you still can't log in after that, and I'll see if something's up with the Google Drive integration. Last time I checked it was working fine, but I'll give it a look if you guys are still having issues.

this is the result of attempting to add google drive via `drive.google.com`
![image](https://user-images.githubusercontent.com/122128828/217936770-a8f8a5f5-ac40-437f-911a-84702b2e5c1f.png)

**Comment by FabioLolix** [comment]
Didn't work, the program is completely blocked by google, got the same message as gonzo

Since it was a lot of time that I didn't use rclone I followed the guide https://rclone.org/drive/#making-your-own-client-id to make my personal gdrive id and worked (it complained that the program was not verified but let me continue), after I copied rclone.conf to /.config/celeste/ and tried again nothing changed

>  I'm gonna look into it tonight and try to get a fix in

Take your time :)

**Comment by hwittenborn** [comment]
@gonzoknows @FabioLolix: See https://github.com/hwittenborn/celeste/issues/30#issuecomment-1424941394 for why Google Drive integration is currently failing.

**Comment by gonzoknows** [comment]
> @gonzoknows @FabioLolix: See [#30 (comment)](https://github.com/hwittenborn/celeste/issues/30#issuecomment-1424941394) for why Google Drive integration is currently failing.

okay thank you

**Comment by hwittenborn** [comment]
Gonna go ahead and close this since it's now being fully tracked via https://github.com/hwittenborn/celeste/issues/30#issuecomment-1444162537.

The port issue mentioned in https://github.com/hwittenborn/celeste/issues/43#issuecomment-1424614573 show now be fixed as well.
