### ISSUE TITLE
Password isn't allowed to contain `:`

### ISSUE THREAD

**Issue by Maryjane-ai** [hwittenborn/celeste#48]
When trying to connect to a nextcloud account, celeste does not allow me to log in because it states that it cannot allow passwords with the char: `:`

My nextcloud provider allows passwords with `:`

![celeste](https://user-images.githubusercontent.com/55666718/218286372-1449c5a7-f981-443c-8e03-47330aa20baa.png)

**Comment by Maryjane-ai** [comment]
My guess is that it is caused by this line: 

https://github.com/hwittenborn/celeste/blob/765dfa25c5ce5a52bcaf347e94c8e8de5f27972b/celeste/src/login/login_util.rs#L111

**Comment by hwittenborn** [comment]
That's correct @Maryjane-ai - I don't recall why I made that a requirement when it doesn't appear to be needed. Would you want to make a PR removing that bit of code?

I'm pretty sure the username field is affected in the same way if you want to remove that as well.

**Comment by Maryjane-ai** [comment]
@hwittenborn I can make a PR for this.

**Comment by Maryjane-ai** [comment]
@hwittenborn I made this pull request to try to fix this: 

https://github.com/hwittenborn/celeste/pull/50

but rust is not my expertise. So I would appreciate if you could review it.
