### ISSUE TITLE
Window gets larger as more errors start to pile up

### ISSUE THREAD

**Issue by dyskette** [hwittenborn/celeste#53]
The main window of celeste seems to get larger when there is a large list of Synchronization errors. 😿 

![Captura desde 2023-02-18 23-02-17-obfuscated](https://user-images.githubusercontent.com/6687927/219923455-0a500b7f-fef3-4720-b882-be372a2a72ab.png)

**Comment by hwittenborn** [comment]
Thanks for reporting the issue! It should definitely be scrolling once it gets long enough, I'll get a fix going for that shortly.

**Comment by hwittenborn** [comment]
The fix for this is being deployed right now, it should be out to the MPR and Snapcraft in about 30 minutes, and Flatpak in a few hours.

**Comment by hwittenborn** [comment]
There was some issues with the deployment, so I have to wait for another round of the CI to run. I'm about to head to bed though (and Flatpak deployments currently have to be done manually), so it'll be deployed to Flathub tomorrow, and the MPR/Snapcraft in about 30 minutes still.
