### ISSUE TITLE
Better appadata summary

### ISSUE THREAD

**Issue by bertob** [hwittenborn/celeste#55]
The current summary "GUI file synchronization client that can sync with any cloud provider" could be better (too long, not a call to action, too many details).

I'd suggest something short and simple, e.g. "Sync your cloud files".

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by hwittenborn** [comment]
Thanks for the recommendation! I think I saw that page at some point, I just got caught up with other stuff and then forgot about it. I'll get that fixed up real quick though.
