### ISSUE TITLE
Crash during sync due to unreachable code

### ISSUE THREAD

**Issue by nboughton** [hwittenborn/celeste#61]
Host OS: Fedora Silverblue
Celeste Version: 0.4.1 flatpak
Remote provider: Google Drive
Error: Celeste crashed during sync with the following message:
![Screenshot from 2023-02-24 23-48-49](https://user-images.githubusercontent.com/8879583/221327684-26084fad-afaa-4647-acf6-887be152b4c7.png)

**Comment by hwittenborn** [comment]
Just remembered, but it looks like #49 is the same issue. I still haven't been able to reproduce the issue - could you try following the instructions in https://github.com/hwittenborn/celeste/issues/49#issuecomment-1427045034? If you still get problems just send a message in that issue.
