### ISSUE TITLE
Unknown error code 2310:33

### ISSUE THREAD

**Issue by gonzoknows** [hwittenborn/celeste#62]
## System Details:
OS - [VanillaOS](https://vanillaos.org/) 
Installation - Flatpak (v0.4.6)

![image](https://user-images.githubusercontent.com/122128828/221344379-e9e5a82e-3fdd-4e24-b971-8033f6614da1.png)

## **Error 2310:33**
~~~
thread 'main' panicked at 'internal error: entered unreachable code', celeste/src/launch.rs:2310:33 stack backtrace:
~~~

![image](https://user-images.githubusercontent.com/122128828/221385467-1e3c94ea-2f32-43d8-a009-5df9e26a6ee0.png)

Details:
The problem happens when celeste is launched and begins syncing with Google Drive remotely. 

![image](https://user-images.githubusercontent.com/122128828/221344230-fee17e98-0871-45c8-bf6f-38db6b9668b5.png)

**Comment by hwittenborn** [comment]
This looks like the same issue as https://github.com/hwittenborn/celeste/issues/49 - let me know if you think otherwise, if not just keep track of that issue for when a fix gets in.
