### ISSUE TITLE
Memory leak when displays are not connected

### ISSUE THREAD

**Issue by crimist** [hwittenborn/celeste#72]
When locking my computer (Super+Escape), after the displays turn off Celeste begins to leak memory at a rate of 50mb/s until the computer is OOM.

Here is a screenshot after locking GDM for around a minute.

![image](https://user-images.githubusercontent.com/20033376/222109693-d52c9978-9ccf-465e-97ce-ae9e86649cb1.png)

* Kernel 6.2.1
* GDM 43.0
* Celeste 0.4.6

**Comment by hwittenborn** [comment]
Hey @crimist, are you still experiencing this issue on the latest release of Celeste? I'm suspecting it's due to Celeste' old tray implementation, which has since been redone.

**Comment by crimist** [comment]
Unable to reproduce. Thanks for fixing!

* Linux 6.5.8
* GNOME 45.0
* Celeste 0.8.0
