### ISSUE TITLE
Dropbox can't be set up because the app is pending review

### ISSUE THREAD

**Issue by andradei** [hwittenborn/celeste#76]
Just installed the app and tried to setup Dropbox connection and got this:
![image](https://user-images.githubusercontent.com/2653546/223017419-1242e284-2ebb-4352-8d34-52abfc6ac5d1.png)

**Comment by andradei** [comment]
Also, the app freezes and throws an error right after closing and re-opening
![image](https://user-images.githubusercontent.com/2653546/223017518-a7c37c7d-4b7a-48d6-821f-2ee98f4c9530.png)

**Comment by hwittenborn** [comment]
I think I got an email from Dropbox a bit ago about that, I'm pretty sure I need to resubmit Celeste for review to Dropbox. I'll get that done once I get home later today. 

I'm probably also going to dismiss that error unless it happens even with the Dropbox integration working normally. Let me know if you can find it in any other scenarios though, otherwise I'll just focus on getting the Dropbox issue itself fixed.

**Comment by jamu85** [comment]
I faced the same issue yesterday. Is there any update on this?

**Comment by hwittenborn** [comment]
Hey @jamu85 - I've been meaning to get this looked at but I've been a bit busy getting some other stuff tackled, as well as getting my schedule figured out while balancing all this with college.

I had reached out to Dropbox a few times, but they had some things they wanted changed in my app. Inevitably I'd get a bit busy soon after, and then I'd forget about reaching back to them about their concerns. I need to set a few days aside to just focus on getting it done, but I haven't had much of an opportunity for that recently.

I plan on working on Celeste a fair bit this weekend though, and I'll see if I can get this fixed up then.

**Comment by hwittenborn** [comment]
I've just reached out to Dropbox's support team, and I plan on getting this fixed up this weekend. I'll be relatively free time-wise, so I should be able to get back with them on whatever they need fixed up.

**Comment by hwittenborn** [comment]
@andradei @jamu85 @jrstrick @rastarr: I just got an email back from Dropbox saying that Celeste should be approved now - could one of y'all verify if everything works? I'd check on my end but I'm pretty sure it lets me bypass review checks since I made the Dropbox app.

**Comment by andradei** [comment]
@hwittenborn It's awesome that you worked on this! At the moment I'm using KDE with native Dropbox integration with not a lot of time myself to test.

**Comment by andradei** [comment]
If the others don't respond in a while, it should be okay to close the issue.

**Comment by hwittenborn** [comment]
Thanks for the update @andradei! I'll go ahead and get this issue closed up - if any of y'all end up having issues though, just let me know and I can give this another look.
