### ISSUE TITLE
Faster file syncing needed

### ISSUE THREAD

**Issue by gonzoknows** [hwittenborn/celeste#77]
I don't know if anyone else is experiencing how slow it is to upload a [Cryptomator](https://cryptomator.org/) drive to Google cloud, but it's taken hours for a drive with less than a 1 GB. Considering I have 300mpbs internet this should have been done hours ago.

**Comment by hwittenborn** [comment]
Some others are having the same issue in #64. I'm still looking into it, track that issue for any updates though.
