### ISSUE TITLE
Celeste crashing when syncing Google Drive

### ISSUE THREAD

**Issue by rolandixor** [hwittenborn/celeste#98]
It keeps giving this error without a stack trace:

`thread 'main' panicked at 'internal error: entered unreachable code', celeste/src/launch.rs:2330:33`

It's also saying that the directory isn't found.

**Comment by hwittenborn** [comment]
I'm pretty sure this is the same issue as #49, which I'm still trying to figure out. Feel free to comment on there if you want, or lmk if you think this is something else and I can get this reopened.
